---
- name: setup flipper
  hosts: localhost
  vars:
    sdcard: /Volumes/FLIPPER
    tmpdir: '{{ playbook_dir }}/tmp'
  tasks:
    - name: Clear tmpdir
      ansible.builtin.file:
        path: '{{ tmpdir }}'
        state: absent
# FILES
    - name: IRDB clone
      ansible.builtin.git:
        repo: https://github.com/logickworkshop/Flipper-IRDB.git
        dest: '{{ tmpdir }}/irdb/infrared'
        depth: 1
    - name: IRDB copy
      ansible.posix.synchronize:
        src: '{{ tmpdir }}/irdb/'
        dest: '{{ sdcard }}'
    - name: BadUSB 1 clone
      ansible.builtin.git:
        repo: https://github.com/UNC0V3R3D/Flipper_Zero-BadUsb.git
        dest: '{{ tmpdir }}/uncovered/badusb'
        depth: 1
    - name: BadUSB 1 copy
      ansible.posix.synchronize:
        src: '{{ tmpdir }}/uncovered/'
        dest: '{{ sdcard }}'
    - name: BadUSB 2 clone
      ansible.builtin.git:
        repo: https://github.com/FalsePhilosopher/badusb.git
        dest: '{{ tmpdir }}/falsephilosopher/badusb'
        depth: 1
    - name: BadUSB 2 copy
      ansible.posix.synchronize:
        src: '{{ tmpdir }}/falsephilosopher/'
        dest: '{{ sdcard }}'
    - name: Amiibo clone
      ansible.builtin.git:
        repo: https://github.com/Gioman101/FlipperAmiibo.git
        dest: '{{ tmpdir }}/amiibo/nfc/amiibo'
        depth: 1
    - name: Amiibo copy
      ansible.posix.synchronize:
        src: '{{ tmpdir }}/amiibo/'
        dest: '{{ sdcard }}'
    - name: TouchTunes clone
      ansible.builtin.git:
        repo: https://github.com/jimilinuxguy/flipperzero-touchtunes.git
        dest: '{{ tmpdir }}/touchtunes/subghz/touchtunes'
    - name: TouchTunes copy
      ansible.posix.synchronize:
        src: '{{ tmpdir }}/touchtunes/'
        dest: '{{ sdcard }}'
    - name: T119 clone
      ansible.builtin.git:
        repo: https://github.com/xb8/t119bruteforcer.git
        dest: '{{ tmpdir }}/t119_restaurant/subghz/t119_restaurant'
    - name: T119 copy
      ansible.posix.synchronize:
        src: '{{ tmpdir }}/t119_restaurant/'
        dest: '{{ sdcard }}'
    - name: CustServ clone
      ansible.builtin.git:
        repo: https://github.com/DRA6N/SubGhz_Cust_Serv.git
        dest: '{{ tmpdir }}/custserv/subghz/custserv'
    - name: CustServ copy
      ansible.posix.synchronize:
        src: '{{ tmpdir }}/custserv/'
        dest: '{{ sdcard }}'
# APPS
    - name: Safecracking
      ansible.builtin.get_url:
        url: https://github.com/H4ckd4ddy/flipperzero-sentry-safe-plugin/releases/download/v1.1/Sentry_Safe.fap
        dest: '{{ sdcard }}/apps/'
    - name: Minesweeper
      ansible.builtin.get_url:
        url: https://github.com/panki27/minesweeper/releases/download/v1.2/minesweeper_official.fap
        dest: '{{ sdcard }}/apps/'
    - name: Pomodoro
      ansible.builtin.get_url:
        url: https://github.com/Th3Un1q3/flipp_pomodoro/releases/download/v2.0.7/flipp_pomodoro_standard_23.0.fap
        dest: '{{ sdcard }}/apps/'
