---
- name: install sonic robo battle 2
  hosts: steamdeck
  become: yes
  tasks:
    - name: start ssh
      ansible.builtin.systemd:
        state: started
        name: sshd
    - name: install sonic robo battle 2
      community.general.flatpak:
        name:
          - org.srb2.SRB2
    - name: grab sonic robo battle 2 sonic 2006
      ansible.builtin.get_url:
        url: https://mb.srb2.org/addons/sonic-2006-extended-port.157/version/5236/download?file=57797
        dest: /home/deck/.var/app/org.srb2.SRB2/.srb2/addons/sonic2006.pk3
    - name: grab sonic robo battle 2 angel island tour
      ansible.builtin.get_url:
        url: https://mb.srb2.org/addons/angel-island-tour.3131/download
        dest: /home/deck/.var/app/org.srb2.SRB2/.srb2/addons/angel_island.pk3
    - name: grab sonic robo battle 2 emerald quest
      ansible.builtin.get_url:
        url: https://mb.srb2.org/addons/emerald-quest.4605/download
        dest: /home/deck/.var/app/org.srb2.SRB2/.srb2/addons/emerald_quest.pk3
